<?binding.jca materiasCursando_db.jca?>
<wsdl:definitions name="materiasCursando" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/jugar/Project3/materiasCursando" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/jugar/Project3/materiasCursando" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/materiasCursando">
    <plt:partnerLinkType name="materiasCursando_plt">
        <plt:role name="materiasCursando_role">
            <plt:portType name="tns:materiasCursando_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/materiasCursando" schemaLocation="xsd/materiasCursando_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="materiasCursandoSelect_inputParameters">
        <wsdl:part name="materiasCursandoSelect_inputParameters" element="top:materiasCursandoSelect_paramInputParameters"/>
    </wsdl:message>
    <wsdl:message name="InscriptosCollection_msg">
        <wsdl:part name="InscriptosCollection" element="top:InscriptosCollection"/>
    </wsdl:message>
    <wsdl:portType name="materiasCursando_ptt">
        <wsdl:operation name="materiasCursandoSelect">
            <wsdl:input message="tns:materiasCursandoSelect_inputParameters"/>
            <wsdl:output message="tns:InscriptosCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
