<?binding.jca MateriasIsncripto_db.jca?>
<wsdl:definitions name="MateriasIsncripto" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/jugar/Project3/MateriasIsncripto" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/jugar/Project3/MateriasIsncripto" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MateriasIsncripto">
    <plt:partnerLinkType name="MateriasIsncripto_plt">
        <plt:role name="MateriasIsncripto_role">
            <plt:portType name="tns:MateriasIsncripto_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MateriasIsncripto" schemaLocation="xsd/MateriasIsncripto_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MateriasIsncriptoSelect_inputParameters">
        <wsdl:part name="MateriasIsncriptoSelect_inputParameters" element="top:MateriasIsncriptoSelect_paramInputParameters"/>
    </wsdl:message>
    <wsdl:message name="InscriptosCollection_msg">
        <wsdl:part name="InscriptosCollection" element="top:InscriptosCollection"/>
    </wsdl:message>
    <wsdl:portType name="MateriasIsncripto_ptt">
        <wsdl:operation name="MateriasIsncriptoSelect">
            <wsdl:input message="tns:MateriasIsncriptoSelect_inputParameters"/>
            <wsdl:output message="tns:InscriptosCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
